[workspace]
members = [
    "utils",
    "easy/count-items-matching-a-rule",
    "easy/decode-xored-array",
    "easy/maximum-nesting-depth-of-the-parentheses",
    "easy/check-if-two-string-arrays-are-equivalent",
    "easy/design-an-ordered-stream",
    "easy/sum-of-all-odd-length-subarrays",
]